## Rate of change

### Last modified?

In [2]:
import pandas as pd
import altair as alt

from utils import pgp_csv_paths, chart_dir

documents = pd.read_csv(pgp_csv_paths["documents"])

In [3]:
# parse initial entry as date time
documents['last_modified'] = pd.to_datetime(documents['last_modified'], format='ISO8601')

In [4]:
docs_modified = documents.groupby(pd.Grouper(key="last_modified", freq="W-MON"))[['pgpid']].count().reset_index().rename(columns={'pgpid': 'total'})
docs_modified.head()

              last_modified  total
0 2021-05-31 00:00:00+00:00   7034
1 2021-06-07 00:00:00+00:00      3
2 2021-06-14 00:00:00+00:00     42
3 2021-06-21 00:00:00+00:00     20
4 2021-06-28 00:00:00+00:00     39

In [5]:
# TODO rename total/cumulative total so they make sense here
docs_modified_chart = alt.Chart(docs_modified).mark_area().encode(
    y=alt.Y('total', title="Documents").scale(domain=[0, 800], clamp=True),
    x=alt.X('last_modified', title="Last Modified", axis=alt.Axis(format="%Y", tickCount="year")),
    # color=alt.Color("status", title="").scale(scheme="tableau20"),
).properties(
    width=900,
    height=200
)

docs_modified_chart.save(f'{chart_dir}/docs_last_modified.pdf')
docs_modified_chart

alt.Chart(...)

### Stats from GitHub versions

PGP metadata is backed up to a GitHub repository. We can use the repository history to assess the rate of change.

In [6]:
dataset_stats = pd.read_csv("../dataset-history/pgp-dataset-history.csv")

dataset_stats.head()

         date       type  count
0  2026-02-24  documents  35855
1  2026-02-23  documents  35854
2  2026-02-22  documents  35854
3  2026-02-21  documents  35857
4  2026-02-20  documents  35856

In [52]:
doc_frag_totals = dataset_stats[dataset_stats.type.isin(['documents', 'fragments', 'fragment_images'])]

totals_by_time = alt.Chart(doc_frag_totals).mark_line().encode(
    y=alt.Y('count', title="Total").scale(domain=[15000, 40000]),
    x=alt.X('date:T', title="", axis=None),   # hide so we don't duplicate when combined #alt.Axis(format="%Y", tickCount="year")),
    color=alt.Color("type", title="").scale(scheme="tableau10"),
).properties(
    width=900,
    height=250
# can't configure legend here because we want to combine
)
totals_by_time

alt.Chart(...)

In [55]:
text_totals = dataset_stats[dataset_stats.type.isin(['transcriptions', 'translations', 'people', 'places'])]

text_totals_by_time = alt.Chart(text_totals).mark_line().encode(
    y=alt.Y('count', title=""),
    x=alt.X('date:T', title="Date", axis=alt.Axis(format="%Y", tickCount="year")),
    color=alt.Color("type", title="") # .scale(scheme="tableau10", reverse=True),
).properties(
    width=900,
    height=150
)
text_totals_by_time

alt.Chart(...)

In [59]:
combined_totals = (totals_by_time & text_totals_by_time).configure_legend(
    strokeColor='gray',
    fillColor='white', #EEEEEE',
    padding=15,
    cornerRadius=5,
    # orient='top-left',
    orient='none',
    legendX=750, legendY=60,
)

combined_totals.save(f'{chart_dir}/combined_totals_historic.pdf')
combined_totals

alt.VConcatChart(...)